save_score:
    path: /score/save
    controller: App\Controller\ScoreController::save
    methods: POST

show_score:
    path: /score/show
    controller: App\Controller\ScoreController::show
    methods: GET